### ISSUE TITLE
Quick question, esformatter working on the browser

### ISSUE THREAD

**Issue by ruyadorno** [lloiser/esformatter-visualize#1]
How did you made the bundle?

**Comment by ruyadorno** [comment]
I suppose you have used browserify or something similar, I was just curious as I was working on the same thing :)

**Comment by lloiser** [comment]
`browserify -r esformatter-quotes -r esformatter-braces -r esformatter-semicolons esformatter-exports.js > bundled.js`
`-r ...` is necessary for plugins to be correctly "loaded"

**Comment by lloiser** [comment]
and esformatter-exports simply exports some of the esformatter functions to the window

**Comment by ruyadorno** [comment]
nice! thanks for the detailed description!
