### ISSUE TITLE
Bundle is broken

### ISSUE THREAD

**Issue by paulovieira** [lloiser/esformatter-visualize#2]
The visualizer is not working at the moment. Nothing happens when the user clicks the arrow button to see the output. The console shows an error:

``` javascript
Uncaught Error: Line 4: Unexpected token ( 
```

**Comment by paulovieira** [comment]
Sorry. It was my example that had bad syntax. I didn't know esformatter would throw an error in that case.

**Comment by airtonix** [comment]
Still broken. doesn't like es6 keyword `import`

UX of this needs improvement... even just an alert telling me why it won't format something.
